### ISSUE TITLE
clang_parser fails with 5.2.0 kernel headers

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#727]
I bisected it to this commit.. it's the diagnostic check loop,
that takes it down for me:

```
  for (unsigned int i=0; i < clang_getNumDiagnostics(handler.get_translation_unit()); i++) {
    CXDiagnostic diag = clang_getDiagnostic(handler.get_translation_unit(), i);
    CXDiagnosticSeverity severity = clang_getDiagnosticSeverity(diag);
    if (severity == CXDiagnostic_Error || severity == CXDiagnostic_Fatal) {
      if (bt_debug >= DebugLevel::kDebug)
        std::cerr << "Input (" << input.size() << "): " << input << std::endl;
      return false;
    }
  } 
```

my env:
```
[root@dell-r440-01 build]# clang --version
clang version 8.0.0 (Fedora 8.0.0-1.fc30)
[root@dell-r440-01 build]# uname -a
Linux dell-r440-01.lab.eng.brq.redhat.com 5.2.0-rc1+ #20 SMP Fri May 31 15:20:54 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

this is the output:
```
[root@dell-r440-01 build]# bpftrace  ../bpftrace/tools/runqlat.bt 2>&1
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/bitops.h:209:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/bitops.h:255:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/bitops.h:308:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/jump_label.h:23:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/jump_label.h:39:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:85:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:125:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:139:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:154:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:76:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:118:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:132:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:147:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:537:17: warning: taking address of packed member 'sp0' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/cpufeature.h:168:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/preempt.h:94:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/qspinlock.h:23:8: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qspinlock.h:74:55: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qspinlock.h:87:52: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qrwlock.h:74:56: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qrwlock.h:101:53: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/refcount.h:70:13: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/refcount.h:84:13: error: 'asm goto' constructs are not supported yet
```

_Originally posted by @olsajiri in https://github.com/iovisor/bpftrace/issues/653#issuecomment-497923616_

**Comment by mmarchini** [comment]
Duplicate of #611
