### ISSUE TITLE
breakage when building on ubuntu 18.04 with today's bpftrace tip

### ISSUE THREAD

**Issue by ColinIanKing** [iovisor/bpftrace#436]
Info:
``
king@ubuntu:~/bpftrace/build$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
king@ubuntu:~/bpftrace/build$ clang-6.0 -v
clang version 6.0.1-svn334776-1~exp1~20190124082834.118 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
``
Explicitly followed the INSTALL.md notes, make fails as follows:

```
king@ubuntu:~/bpftrace/build$ make
[  1%] [FLEX][flex_lexer] Building scanner with flex 2.6.4
src/lexer.l:51: warning, rule cannot be matched
[  2%] [BISON][bison_parser] Building parser with bison 3.0.4
Scanning dependencies of target parser
[  3%] Building CXX object CMakeFiles/parser.dir/parser.tab.cc.o
/home/king/bpftrace/build/parser.tab.cc: In member function ‘virtual std::__cxx11::string bpftrace::Parser::yysyntax_error_(bpftrace::Parser::state_type, const symbol_type&) const’:
/home/king/bpftrace/build/parser.tab.cc:1507:12: warning: switch missing default case [-Wswitch-default]
     switch (yycount)
            ^
[  4%] Building CXX object CMakeFiles/parser.dir/lex.yy.cc.o
/home/king/bpftrace/build/lex.yy.cc: In function ‘bpftrace::Parser::symbol_type yylex(bpftrace::Driver&, yyscan_t)’:
/home/king/bpftrace/build/lex.yy.cc:1447:15: warning: switch missing default case [-Wswitch-default]
   else switch ( yy_get_next_buffer( yyscanner ) )
               ^
[  5%] Linking CXX static library libparser.a
[  5%] Built target parser
[  6%] Building CXX object src/arch/CMakeFiles/arch.dir/x86_64.cpp.o
[  7%] Linking CXX static library libarch.a
[  7%] Built target arch
Scanning dependencies of target ast
[  9%] Building CXX object src/ast/CMakeFiles/ast.dir/ast.cpp.o
[ 10%] Building CXX object src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o
In file included from /usr/lib/llvm-6.0/include/llvm/Support/Error.h:21:0,
                 from /usr/lib/llvm-6.0/include/llvm/ExecutionEngine/JITSymbol.h:24,
                 from /usr/lib/llvm-6.0/include/llvm/ExecutionEngine/ExecutionEngine.h:24,
                 from /home/king/bpftrace/src/bpforc.h:3,
                 from /home/king/bpftrace/src/ast/codegen_llvm.cpp:1:
/usr/lib/llvm-6.0/include/llvm/Config/abi-breaking.h:23:6: warning: "LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING" is not defined, evaluates to 0 [-Wundef]
 #if !LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/king/bpftrace/src/ast/codegen_llvm.h:8:0,
                 from /home/king/bpftrace/src/ast/codegen_llvm.cpp:2:
/home/king/bpftrace/src/ast/irbuilderbpf.h:5:10: fatal error: bcc_usdt.h: No such file or directory
 #include "bcc_usdt.h"
          ^~~~~~~~~~~~
compilation terminated.
src/ast/CMakeFiles/ast.dir/build.make:86: recipe for target 'src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o' failed
make[2]: *** [src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o] Error 1
CMakeFiles/Makefile2:1138: recipe for target 'src/ast/CMakeFiles/ast.dir/all' failed
make[1]: *** [src/ast/CMakeFiles/ast.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
``

**Comment by brendangregg** [comment]
I believe the missing bcc_usdt.h is from using an old version of libbcc/libbpfcc, eg, 0.5.0, instead of something newer like 0.8.0.

**Comment by ColinIanKing** [comment]
OK, that's going to be tricky with a bog-standard build on 18.04. I wonder how it builds for you, as the notes clearly indicates that it builds on 18.04.

**Comment by ColinIanKing** [comment]
Thanks @brendangregg - I've got this sorted now.  Ubuntu is packaging bpftrace as a snap, so all the necessary dependencies are bundled together; this means the latest code will run on Xenial upwards with the same snap.  https://snapcraft.io/bpftrace
