### ISSUE TITLE
Several warning and errors when running tools

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#670]
```
# ./src/bpftrace ../tools/tcpconnect.bt
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:26:42: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:28:2: warning: implicit declaration of function 'WRITE_ONCE' is invalid in C99 [-Wimplicit-function-declaration]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:28:17: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:26:42: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:29:6: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:26:42: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:38:15: error: unknown type name 'bool'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:38:44: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:42:9: error: use of undeclared identifier 'true'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:44:15: error: unknown type name 'bool'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:44:50: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:46:9: error: use of undeclared identifier 'true'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:63:6: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:64:5: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:65:5: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:66:2: warning: implicit declaration of function 'WRITE_ONCE' is invalid in C99 [-Wimplicit-function-declaration]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:66:17: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:77:36: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:79:28: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:77:36: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:91:41: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:93:22: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:91:41: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:103:38: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:105:6: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:103:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:106:2: warning: implicit declaration of function 'WRITE_ONCE' is invalid in C99 [-Wimplicit-function-declaration]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:106:17: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:103:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:44: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:120:18: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:44: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:120:31: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:44: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:123:36: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:125:19: warning: incompatible pointer types passing 'struct list_head *' to parameter of type 'struct list_head *' [-Wincompatible-pointer-types]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:55: note: passing argument to parameter 'entry' here
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:126:7: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:123:36: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:127:7: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:123:36: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:137:40: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:140:5: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:137:40: note: forward declaration of 'struct list_head'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
Unknown identifier: 'AF_INET'
Unknown identifier: 'AF_INET6'
Unknown identifier: 'AF_INET'

```

I thought it was something on my machine, but then I got back to the last commit I knew this was working, and:

```
# ./src/bpftrace ../tools/tcpconnect.bt
Tracing tcp connections. Hit Ctrl-C to end.
TIME     PID      COMM             SADDR                                   SPORT  DADDR                                   DPORT 
```

So I used `git bisect` and the first commit with this failure is 32dd14b74aa315ac9f0c39f8ea97fe54b4325c78:

```
32dd14b74aa315ac9f0c39f8ea97fe54b4325c78 is the first bad commit
commit 32dd14b74aa315ac9f0c39f8ea97fe54b4325c78
Author: Javier Honduvilla Coto <javierhonduco@gmail.com>
Date:   Sun May 19 01:02:06 2019 +0200

    Add /usr/include to header search path
    
    Added two runtime tests:
    ```
    [...]
    [ RUN      ] basic.libraries under /usr/include are in the search path
    [       OK ] basic.libraries under /usr/include are in the search path
    [ RUN      ] basic.non existent library include fails
    [       OK ] basic.non existent library include fails
    [----------] 17 tests from basic
    [...]
    ```

:040000 040000 28b8fa26e39c2ff7fb154cad4d8cd9cd642e5bcf 73b20cdb11e57843ae3e4fd0496e317543296743 M      src
:040000 040000 7bcc8adc429f822299d6d3043b18e0182dedd2ba 25b2d047f8014b6346ebb057ceaa9b6562053919 M      tests
```

Anyone else having this problem?

**Comment by caringi** [comment]
@mmarchini I think this PR fixes this problem:

https://github.com/iovisor/bpftrace/pull/657

**Comment by javierhonduco** [comment]
@mmarchini Yeah, my bad :cry: Will submit a PR to detect this kind of bugs in the future. Created #655 to keep track of it :)

**Comment by mmarchini** [comment]
It would be detected by the `tools-parsing-test` suite, but since we can't run it on Travis it's easy to miss.

**Comment by javierhonduco** [comment]
Did not know this script, seems very useful, thanks! Unfortunately it would not have shown this issue I think:

```shell
$ sudo src/bpftrace -d ../tools/tcpconnect.bt |& grep -i error | head -3
/lib/modules/4.16.4-1-ARCH/build/include/linux/list.h:28:17: error: incomplete definition of type 'struct list_head'
/lib/modules/4.16.4-1-ARCH/build/include/linux/list.h:29:6: error: incomplete definition of type 'struct list_head'
/lib/modules/4.16.4-1-ARCH/build/include/linux/list.h:38:15: error: unknown type name 'bool'

$ sudo src/bpftrace -d ../tools/tcpconnect.bt > /dev/null 2>&1
$ echo $?
0
```

#653 to track this ([context](https://github.com/iovisor/bpftrace/pull/652#issuecomment-493713657))

**Comment by mmarchini** [comment]
Probably an environment difference, because on my machine clang crashes due to `too many errors`:

```
sudo src/bpftrace -d ../tools/tcpconnect.bt
...
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:26:42: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:28:2: warning: implicit declaration of function 'WRITE_ONCE' is invalid in C99 [-Wimplicit-function-declaration]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:28:17: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:26:42: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:29:6: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:26:42: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:38:15: error: unknown type name 'bool'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:38:44: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:42:9: error: use of undeclared identifier 'true'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:44:15: error: unknown type name 'bool'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:44:50: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:46:9: error: use of undeclared identifier 'true'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:63:6: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:64:5: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:65:5: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:66:2: warning: implicit declaration of function 'WRITE_ONCE' is invalid in C99 [-Wimplicit-function-declaration]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:66:17: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:56:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:77:36: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:79:28: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:77:36: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:91:41: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:93:22: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:91:41: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:103:38: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:105:6: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:103:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:106:2: warning: implicit declaration of function 'WRITE_ONCE' is invalid in C99 [-Wimplicit-function-declaration]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:106:17: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:103:38: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:44: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:120:18: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:44: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:120:31: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:44: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:123:36: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:125:19: warning: incompatible pointer types passing 'struct list_head *' to parameter of type 'struct list_head *' [-Wincompatible-pointer-types]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:115:55: note: passing argument to parameter 'entry' here
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:126:7: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:123:36: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:127:7: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:123:36: note: forward declaration of 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:137:40: warning: declaration of 'struct list_head' will not be visible outside of this function [-Wvisibility]
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:140:5: error: incomplete definition of type 'struct list_head'
/lib/modules/4.15.0-47-generic/build/include/linux/list.h:137:40: note: forward declaration of 'struct list_head'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
Unknown identifier: 'AF_INET'
Unknown identifier: 'AF_INET6'
Unknown identifier: 'AF_INET'

$ echo $?
1
```

**Comment by mmarchini** [comment]
Fixed by #657
