### ISSUE TITLE
Should return error if #include can't be found

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#653]
```
#include <blah.h>
BEGIN { 1 }
```

When run, this program displays the "fatal" error but then carries on:
```
[alastair@arch build-debug]$ sudo ./src/bpftrace test.bt 
definitions.h:2:10: fatal error: 'blah.h' file not found
Attaching 1 probe...
^C
```

**Comment by mmarchini** [comment]
This makes sense, but will probably break some tools, so I'd rather have this implemented sooner than later. Aiming to get this done in the next version, but implementation is proving more challenging than I expected.

In theory `clang_parseTranslationUnit2` should return an error code in that case, but apparently it doesn't... Not sure if that's some misconfiguration on our side or a bug (or if that's how it's supposed to work). `CXFile` (which we can get from the current cursor) doesn't seem to have information on where a file exists or not. 

Trying to find alternatives. `clang_indexTranslationUnit` is always returning an error code, even for valid code. Maybe we can ignore the return of `clang_indexTranslationUnit` and use one of the callbacks to detect if a file is missing? This information might be reachable somehow in the `diagnostic` callback.

**Comment by mmarchini** [comment]
Ok, I was able to get this working with `clang_getNumDiagnostics(CXTranslationUnit)` and `clang_getDiagnostic(CXTranslationUnit, unsigned)`, but now bpftrace will fail for structs with fields with incomplete types as well (`struct Foo { struct bar foo } BEGIN { 1 }`). bpftrace should not fail unless it's using a struct affected by a incomplete type (in which case bpftrace won't be able to calculate the offsets correctly, see #537). The problem is: I don't know how to distinguish the incomplete type error from the file not found error. I guess we could use `clang_getDiagnosticCategory`, but I don't know how stable the category numbers are, nor where they are documented...

**Comment by mmarchini** [comment]
Our tools are not failing because of this, only one test. I'm inclined to make our parsing stricter and wait until someone finds a use case where this doesn't work before making it more flexible, and if no one hit this we can just keep it strict.

**Comment by olsajiri** [comment]
this one breaks tools/runqlat.bt for me, looks like it fails on clang parser.. checking

**Comment by olsajiri** [comment]
> Ok, I was able to get this working with `clang_getNumDiagnostics(CXTranslationUnit)` and `clang_getDiagnostic(CXTranslationUnit, unsigned)`, but now bpftrace will fail for structs with fields with incomplete types as well (`struct Foo { struct bar foo } BEGIN { 1 }`). bpftrace should not fail unless it's using a struct affected by a incomplete type (in which case bpftrace won't be able to calculate the offsets correctly, see #537). The problem is: I don't know how to distinguish the incomplete type error from the file not found error. I guess we could use `clang_getDiagnosticCategory`, but I don't know how stable the category numbers are, nor where they are documented...

so should instead keep this in place (perhaps not displayed by default) and fail only
during code generation when we reach unknown type?

**Comment by mmarchini** [comment]
runqlat is working for me. Also, IIRC [this comment](https://github.com/iovisor/bpftrace/issues/653#issuecomment-495398639) is outdated/invalid. See my following comment:

> Our tools are not failing because of this

@olsajiri what's your environment? Mine is:

```
# ./src/bpftrace --version
bpftrace v0.9-203-g13fb

# uname -a
Linux laul-mmarchini 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Maybe runqlat is not working because of other changes? We merged quite a few clang parser changes in the past few days.

**Comment by olsajiri** [comment]
I bisected it to this commit.. it's the diagnostic check loop,
that takes it down for me:

```
  for (unsigned int i=0; i < clang_getNumDiagnostics(handler.get_translation_unit()); i++) {
    CXDiagnostic diag = clang_getDiagnostic(handler.get_translation_unit(), i);
    CXDiagnosticSeverity severity = clang_getDiagnosticSeverity(diag);
    if (severity == CXDiagnostic_Error || severity == CXDiagnostic_Fatal) {
      if (bt_debug >= DebugLevel::kDebug)
        std::cerr << "Input (" << input.size() << "): " << input << std::endl;
      return false;
    }
  } 
```

my env:
```
[root@dell-r440-01 build]# clang --version
clang version 8.0.0 (Fedora 8.0.0-1.fc30)
[root@dell-r440-01 build]# uname -a
Linux dell-r440-01.lab.eng.brq.redhat.com 5.2.0-rc1+ #20 SMP Fri May 31 15:20:54 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

this is the output:
```
[root@dell-r440-01 build]# bpftrace  ../bpftrace/tools/runqlat.bt 2>&1
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/bitops.h:209:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/bitops.h:255:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/bitops.h:308:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/jump_label.h:23:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/jump_label.h:39:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:85:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:125:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:139:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic.h:154:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:76:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:118:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:132:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/atomic64_64.h:147:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:537:17: warning: taking address of packed member 'sp0' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/processor.h:554:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/cpufeature.h:168:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/preempt.h:94:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/qspinlock.h:23:8: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qspinlock.h:74:55: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qspinlock.h:87:52: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qrwlock.h:74:56: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/include/asm-generic/qrwlock.h:101:53: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.2.0-rc1+/source/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/refcount.h:70:13: error: 'asm goto' constructs are not supported yet
/lib/modules/5.2.0-rc1+/source/arch/x86/include/asm/refcount.h:84:13: error: 'asm goto' constructs are not supported yet
```

**Comment by olsajiri** [comment]
@mmarchini , what's the logic behind the diagnostics check? I thought bpftrace
wants to fail only if code generation is missing some type info, that's actually
needed for the program to be compiled/run.. missin #include  should not matter, correct?

**Comment by mmarchini** [comment]
> what's the logic behind the diagnostics check?

It's the only way I found to check if an included file exists.

>  I thought bpftrace wants to fail only if code generation is missing some type info, that's actually needed for the program to be compiled/run..

We also want to fail if an included file don't exist. The failure you're getting (`error: 'asm goto' constructs are not supported yet`) should not be happening though. I opened https://github.com/iovisor/bpftrace/issues/727 to investigate this.
