### ISSUE TITLE
bpftrace fails to build on Ubuntu server 18.04

### ISSUE THREAD

**Issue by fgleiser** [iovisor/bpftrace#389]
I just set up a new VM to try some new ebpf features. 
I followed the install.md instructions, installed toolchain from llvm repos but ebpf fails to build, it complains about some missing header file

Scanning dependencies of target ast
[ 46%] Building CXX object src/ast/CMakeFiles/ast.dir/ast.cpp.o
[ 47%] Building CXX object src/ast/CMakeFiles/ast.dir/printer.cpp.o
[ 48%] Building CXX object src/ast/CMakeFiles/ast.dir/irbuilderbpf.cpp.o
[ 50%] Building CXX object src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o
[ 51%] Building CXX object src/ast/CMakeFiles/ast.dir/semantic_analyser.cpp.o
In file included from /home/fer/bpftrace/src/ast/irbuilderbpf.cpp:3:0:
/home/fer/bpftrace/src/ast/irbuilderbpf.h:5:10: fatal error: bcc_usdt.h: No such file or directory
 #include "bcc_usdt.h"
          ^~~~~~~~~~~~
compilation terminated.
src/ast/CMakeFiles/ast.dir/build.make:110: recipe for target 'src/ast/CMakeFiles/ast.dir/irbuilderbpf.cpp.o' failed
make[2]: *** [src/ast/CMakeFiles/ast.dir/irbuilderbpf.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/fer/bpftrace/src/ast/codegen_llvm.h:8:0,
                 from /home/fer/bpftrace/src/ast/codegen_llvm.cpp:2:
/home/fer/bpftrace/src/ast/irbuilderbpf.h:5:10: fatal error: bcc_usdt.h: No such file or directory
 #include "bcc_usdt.h"
          ^~~~~~~~~~~~
compilation terminated.

Here's my sources.list file:

`# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to`
`# newer versions of the distribution.`
`deb http://archive.ubuntu.com/ubuntu bionic main restricted`
`# deb-src http://archive.ubuntu.com/ubuntu bionic main restricted`

`## Major bug fix updates produced after the final release of the`
`## distribution.`
`deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted`
`# deb-src http://archive.ubuntu.com/ubuntu bionic-updates main restricted`

`## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu`
`## team. Also, please note that software in universe WILL NOT receive any`
`## review or updates from the Ubuntu security team.`
`deb http://archive.ubuntu.com/ubuntu bionic universe`
`# deb-src http://archive.ubuntu.com/ubuntu bionic universe`
`deb http://archive.ubuntu.com/ubuntu bionic-updates universe`
`# deb-src http://archive.ubuntu.com/ubuntu bionic-updates universe`

`## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu`
`## team, and may not be under a free licence. Please satisfy yourself as to`
`## your rights to use the software. Also, please note that software in`
`## multiverse WILL NOT receive any review or updates from the Ubuntu`
`## security team.`
`deb http://archive.ubuntu.com/ubuntu bionic multiverse`
`# deb-src http://archive.ubuntu.com/ubuntu bionic multiverse`
`deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse`
`# deb-src http://archive.ubuntu.com/ubuntu bionic-updates multiverse`

`## N.B. software from this repository may not have been tested as`
`## extensively as that contained in the main release, although it includes`
`## newer versions of some applications which may provide useful features.`
`## Also, please note that software in backports WILL NOT receive any review`
`## or updates from the Ubuntu security team.`
`deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse`
`# deb-src http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse`

`## Uncomment the following two lines to add software from Canonical's`
`## 'partner' repository.`
`## This software is not part of Ubuntu, but is offered by Canonical and the`
`## respective vendors as a service to Ubuntu users.`
`# deb http://archive.canonical.com/ubuntu bionic partner`
`# deb-src http://archive.canonical.com/ubuntu bionic partner`

`deb http://archive.ubuntu.com/ubuntu bionic-security main restricted`
`# deb-src http://archive.ubuntu.com/ubuntu bionic-security main restricted`
`deb http://archive.ubuntu.com/ubuntu bionic-security universe`
`# deb-src http://archive.ubuntu.com/ubuntu bionic-security universe`
`deb http://archive.ubuntu.com/ubuntu bionic-security multiverse`
`# deb-src http://archive.ubuntu.com/ubuntu bionic-security multiverse`
`# from https://apt.llvm.org/:`
`deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main`
`deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic main`
`# 5.0`
`deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main`
`deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main`
`# 6.0`
`deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main`
`deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main`

**Comment by gslavin** [comment]
I stumbled across this issue when I was trying to use bpftrace on Ubuntu 18.04.  If you're just trying to use bpftrace, you can install it as an Ubuntu snap package using the link in this comment:

https://github.com/iovisor/bpftrace/issues/436#issuecomment-466669292

**Comment by mmarchini** [comment]
@fgleiser do you still have issues on the latest version and by following the updated install instructions (they were updated in https://github.com/iovisor/bpftrace/pull/596)?

**Comment by mmarchini** [comment]
Closing since there has been no activity for some time and the issue is probably fixed. @gslavin feel free to reopen if the issue persists with the updated install instructions.
