### ISSUE TITLE
BTF doesn't work with libbpf v0.4

### ISSUE THREAD

**Issue by brk0v** [iovisor/bpftrace#1992]
### What reproduces the bug?

Build from trunk:

```
$ git clone https://github.com/iovisor/bpftrace.git
$ cd bpftrace
$ cmake .
```

Output: 

```
...
-- Found LibBpf: /usr/lib/libbpf.so
-- Looking for btf_dump__new
-- Looking for btf_dump__new - not found
-- Looking for btf_dump__emit_type_decl
-- Looking for btf_dump__emit_type_decl - not found
...
```

In `./CMakeFiles/CMakeError.log`
```
Determining if the btf_dump__new exist failed with the following output:
Change Dir: /home/vagrant/bpftrace/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_53627/fast && /usr/bin/make  -f CMakeFiles/cmTC_53627.dir/build.make CMakeFiles/cmTC_53627.dir/build
make[1]: Entering directory '/home/vagrant/bpftrace/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_53627.dir/CheckSymbolExists.c.o
/usr/bin/cc   -include stdbool.h -o CMakeFiles/cmTC_53627.dir/CheckSymbolExists.c.o -c /home/vagrant/bpftrace/CMakeFiles/CMakeTmp/CheckSymbolExists.c
In file included from /home/vagrant/bpftrace/CMakeFiles/CMakeTmp/CheckSymbolExists.c:2:
/usr/include/bpf/btf.h: In function ‘btf_is_float’:
/usr/include/bpf/btf.h:328:31: error: ‘BTF_KIND_FLOAT’ undeclared (first use in this function); did you mean ‘BTF_KIND_CONST’?
  328 |         return btf_kind(t) == BTF_KIND_FLOAT;
      |                               ^~~~~~~~~~~~~~
      |                               BTF_KIND_CONST
/usr/include/bpf/btf.h:328:31: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [CMakeFiles/cmTC_53627.dir/build.make:78: CMakeFiles/cmTC_53627.dir/CheckSymbolExists.c.o] Error 1
make[1]: Leaving directory '/home/vagrant/bpftrace/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_53627/fast] Error 2
```

```
$ zcat /proc/config.gz  | grep CONFIG_DEBUG_INFO_BTF
CONFIG_DEBUG_INFO_BTF=y
CONFIG_DEBUG_INFO_BTF_MODULES=y
```

```
$ ls -l /usr/lib/libbpf.so.0.5.0
-rwxr-xr-x 1 root root 317768 Sep  2 18:45 /usr/lib/libbpf.so.0.5.0
```

**Comment by fbs** [comment]
Which os are you on and where did you get libbpf from?

**Comment by brk0v** [comment]
Thank you for your time and  a prompt reply.

My os is  Arch Linux

```
# uname -a
Linux archlinux 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux
```

I tried `libbpf` from the community repo: https://archlinux.org/packages/extra/x86_64/libbpf/ and from AUR: https://archlinux.org/packages/extra/x86_64/libbpf/

I will try to compile it from the sources if necessary.

**Comment by fbs** [comment]
BTF_KIND_FLOAT is relatively new so if your libbpf bulid is newer than what the kernels libbpf is (libbpf is part of the kernel but also stand alone build that can be a newer version) that might cause issues, but your kernel is up to date too.

What you could try is to build libbpf and run `make install_uapi_headers`, it should install the latest uapi headers which inturns defines the FLOAT. Or you could do a `grep BTF_KIND_FLOAT /usr/include /usr/src /lib/modules/$(uname -r)` and see if it pops up there.

**Comment by brk0v** [comment]
Thank you a lot! You saved my day! 

`make install_uapi_header` fixed my issue. 

```
...
-- Found LibBpf: /usr/lib/libbpf.so
-- Looking for btf_dump__new
-- Looking for btf_dump__new - found
-- Looking for btf_dump__emit_type_decl
-- Looking for btf_dump__emit_type_decl - found
...
```

```
# sudo bpftrace --info 2>&1 | grep btf
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  btf (depends on Build:libbpf): yes
```

**Comment by fbs** [comment]
Not sure whether that is the right solution, afaik those headers should be part of the kernel.
