### ISSUE TITLE
Failed to build script with  include/linux/printk.h

### ISSUE THREAD

**Issue by chenk008** [iovisor/bpftrace#2122]
### What reproduces the bug?
My bpftrace script

```
#!/usr/bin/env bpftrace

#include <linux/sched.h>
#include <linux/cgroup.h>
#include <linux/cgroup-defs.h>

struct rb_root_cached_p {
	void *p1;
	void *p2;
}

struct rt_bandwidth {
	/* nests inside the rq lock: */
	raw_spinlock_t		rt_runtime_lock;
	ktime_t			rt_period;
	u64			rt_runtime;
	struct hrtimer		rt_period_timer;
	unsigned int		rt_period_active;
};

struct cfs_bandwidth {
	raw_spinlock_t		lock;
	ktime_t			period;
	u64			quota;
	u64			runtime;
	s64			hierarchical_quota;
	u64			runtime_expires;
	int			expires_seq;

	short			idle;
	short			period_active;
	struct hrtimer		period_timer;
	struct hrtimer		slack_timer;
	struct list_head	throttled_cfs_rq;

	/* Statistics: */
	int			nr_periods;
	int			nr_throttled;
	u64			throttled_time;

	bool                    distribute_running;
};

struct task_group_p {
	struct cgroup_subsys_state css;


	/* schedulable entities of this group on each CPU */
	struct sched_entity	**se;
	/* runqueue "owned" by this group on each CPU */
	void		**cfs_rq;
	unsigned long		shares;

	/*
	 * load_avg can be heavily contended at clock tick time, so put
	 * it in its own cacheline separated from the fields above which
	 * will also be accessed at each tick.
	 */
	atomic_long_t		load_avg ____cacheline_aligned;


	struct sched_rt_entity	**rt_se;
	void		**rt_rq;

	struct rt_bandwidth	rt_bandwidth;


	struct rcu_head		rcu;
	struct list_head	list;

	struct task_group_p	*parent;
	struct list_head	siblings;
	struct list_head	children;

	struct autogroup	*autogroup;

	struct cfs_bandwidth	cfs_bandwidth;
};

struct cfs_rq_p {
	struct load_weight	load;
	unsigned long		runnable_weight;
	unsigned int		nr_running;
	unsigned int		h_nr_running;

	u64			exec_clock;
	u64			min_vruntime;
	u64			min_vruntime_copy;

	struct rb_root_cached_p	tasks_timeline;

	/*
	 * 'curr' points to currently running entity on this cfs_rq.
	 * It is set to NULL otherwise (i.e when none are currently running).
	 */
	void	*curr;
	void	*next;
	void	*last;
	void	*skip;

	unsigned int		nr_spread_over;

	/*
	 * CFS load tracking
	 */
	struct sched_avg	avg;
	u64			load_last_update_time_copy;
	struct {
		raw_spinlock_t	lock ____cacheline_aligned;
		int		nr;
		unsigned long	load_avg;
		unsigned long	util_avg;
		unsigned long	runnable_sum;
	} removed;

	unsigned long		tg_load_avg_contrib;
	long			propagate;
	long			prop_runnable_sum;

	/*
	 *   h_load = weight * f(tg)
	 *
	 * Where f(tg) is the recursive weight fraction assigned to
	 * this group.
	 */
	unsigned long		h_load;
	u64			last_h_load_update;
	void	*h_load_next;


	void		*rq;	/* CPU runqueue to which this cfs_rq is attached */

	/*
	 * leaf cfs_rqs are those that hold tasks (lowest schedulable entity in
	 * a hierarchy). Non-leaf lrqs hold other higher schedulable entities
	 * (like users, containers etc.)
	 *
	 * leaf_cfs_rq_list ties together list of leaf cfs_rq's in a CPU.
	 * This list is used during load balance.
	 */
	int			on_list;
	struct list_head	leaf_cfs_rq_list;
	struct task_group_p	*tg;	/* group that "owns" this runqueue */
};


kprobe:update_curr
{
    time("%H:%M:%S ");
    $cfs_rq = (struct cfs_rq_p *)arg0;
    $node = (struct kernfs_node *)$cfs_rq->tg->css.cgroup->kn;
    printf("%lu %-16s %d %s\n", $cfs_rq->tg->cfs_bandwidth.quota, comm,pid,
	    str($node->name));
}
```

run script:
```
bpftrace --include /usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/kconfig.h  -I /usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/arch/x86/include/  -I  /usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/  update_curr.bt
```

When I upgrade bpftrace from 0.9 to 0.13, it failed to build this script
```
5.12.1.el8_4.x86_64/include/  update_curr.bt
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/arch/x86/include/asm/bitops.h:134:2: warning: implicit declaration of function 'barrier' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/arch/x86/include/asm/bitops.h:170:2: warning: implicit declaration of function 'barrier' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/bitops.h:65:10: warning: implicit declaration of function 'fls' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/bitops.h:71:26: warning: implicit declaration of function 'hweight32' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/bitops.h:71:41: warning: implicit declaration of function 'hweight64' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/bitops.h:181:10: warning: implicit declaration of function 'fls' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/bitops.h:182:9: warning: implicit declaration of function 'fls64' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/bitops.h:189:10: warning: implicit declaration of function 'fls' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/log2.h:28:9: warning: implicit declaration of function 'fls' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/log2.h:36:9: warning: implicit declaration of function 'fls64' is invalid in C99 [-Wimplicit-function-declaration]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/printk.h:142:28: error: expected parameter declarator
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/printk.h:142:28: error: expected ')'
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/printk.h:142:27: note: to match this '('
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/printk.h:142:19: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
/usr/src/kernels/4.18.0-305.12.1.el8_4.x86_64/include/linux/printk.h:142:33: error: expected ';' after top level declarator
...
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

And this printk.h:142 is below:
```
extern asmlinkage __printf(1, 2)
void early_printk(const char *fmt, ...);
```

Functions  attribute `__printf(1, 2)` cannot be recognized, and it is defined in `include/linux/compiler-gcc.h`, but it does not exist in `include/linux/compiler-clang.h`

### bpftrace --info

```
System
  OS: Linux 4.18.0 #1 SMP Wed Nov 10 04:41:08 UTC 2021
  Arch: x86_64

Build
  version: v0.13.0
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): yes
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
```

**Comment by chenk008** [comment]
It is related to BTF, the new version bpftrace use BTF to compile.
