### ISSUE TITLE
llvm12 + btf build broken

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#2068]
```
 In file included from /home/runner/work/bpftrace/bpftrace/src/btf.cpp:23:
/home/runner/work/bpftrace/bpftrace/src/btf.cpp: In member function 'std::__cxx11::string bpftrace::BTF::c_def(const std::unordered_set<std::__cxx11::basic_string<char> >&) const':
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: error: 'typeof' was not declared in this scope
   dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
          ^~~~~~~~~~~~~
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: note: suggested alternative: 'type_of'
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: error: expected primary-expression before ')' token
   dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
          ^~~~~~~~~~~~~
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: error: '__builtin_types_compatible_p' was not declared in this scope
   dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
          ^~~~~~~~~~~~~
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: note: suggested alternative: '__builtin_ia32_comile'
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: error: expression list treated as compound expression in functional cast [-fpermissive]
   dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
          ^~~~~~~~~~~~~
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: error: expected primary-expression before 'void'
   dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
          ^~~~~~~~~~~~~
/home/runner/work/bpftrace/bpftrace/src/btf.cpp:228:10: error: invalid conversion from 'void*' to 'const btf*' [-fpermissive]
   dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
          ^
```

https://github.com/iovisor/bpftrace/runs/4217466169?check_suite_focus=true

This impact #2066 #2067

**Comment by fbs** [comment]
Rerun of a week old pipeline that worked: https://github.com/iovisor/bpftrace/actions/runs/1439315117/attempts/1 https://github.com/iovisor/bpftrace/actions/runs/1439315117/attempts/2

Only diff i see is

```
2:   OS: Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021
2:   OS: Linux 5.4.0-1062-azure #65~18.04.1-Ubuntu SMP Tue Oct 12 11:26:28 UTC 2021
```

```
1: [ RUN      ] semantic_analyser_btf.kfunc
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: ERROR: BTF: failed to initialize dump (Invalid argument)
1: /home/runner/work/bpftrace/bpftrace/tests/semantic_analyser.cpp:86: Failure
1: Expected equality of these values:
1:   expected_result
1:     Which is: 0
1:   semantics.analyse()
1:     Which is: 1
1: 
1: Input:
1: kfunc:func_1 { $x = args->a; $y = args->foo1; $z = args->foo2->f.a; }
1: 
1: Output:
1: stdin:1:52-65: ERROR: Struct/union of type 'struct Foo2' does not contain a field named 'f'
1: kfunc:func_1 { $x = args->a; $y = args->foo1; $z = args->foo2->f.a; }
1:                                                    ~~~~~~~~~~~~
```

**Comment by martinetd** [comment]
Hello

since this looks like an incompatibility with libbpf 0.6.0 did you bring it up over there?
It looks to me like using typeof() is not very portable and doesn't work from c++

calling `btf_dump__new_deprecated` explicitly instead of `btf_dump__new` fixes the build failure for now, so I assume a workaround with cmake checking if that is available (or the new 0.6.0 one) and using that if possible would work, but the best fix would be to make the macro more portable
(I haven't tried, quick experimenting with __typeof__ or type_of instead didn't bode that well but I didn't insist..)

**Comment by fbs** [comment]
no I haven't. I didn't look into it much, I just wanted to get the build working so other MRs can go in.

Also didn't mean to close this, github auto closed it for us :(

**Comment by martinetd** [comment]
Thanks for the quick reply.
I've asked over in https://github.com/libbpf/libbpf/issues/283 which was the issue which introduced the alternative function and alias; not copying the whole blob but I'm not really sure what to do (thinking from a libbpf standpoint).

Meanwhile for bpftrace the easiest way forward would be to check if `btf_dump__new_deprecated` is declared/defined in cmake and use it instead of `btf_dump__new` for now -- that'll give compatibility with both older libbpf versions and 0.6.0 for now.
Longer-term it could be replaced with `btf_dump__new_v0_6_0` when supporting older versions of libbpf stops being a concern.

**Comment by jeromemarchand** [comment]
Any update on this issue?

I've encountered it on Fedora and can confirm that martinetd proposed patch fixes the compilation issue.

**Comment by viktormalik** [comment]
Should be fixed by #2190.

**Comment by caringi** [comment]
Seems it's not totally fixed yet:
I'm facing the same (or very similar) problem on Fedora 35:

```
In file included from /home/caringi/devel/bpftrace/src/btf.cpp:23:
/home/caringi/devel/bpftrace/src/btf.cpp: In function ‘btf_dump* bpftrace::dump_new(const btf*, btf_dump_printf_fn_t, void*)’:
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: ‘typeof’ was not declared in this scope; did you mean ‘Type’?
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^~~~~~~~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: expected primary-expression before ‘)’ token
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^~~~~~~~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: ‘__builtin_types_compatible_p’ was not declared in this scope
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^~~~~~~~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: expression list treated as compound expression in functional cast [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^~~~~~~~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: expected primary-expression before ‘void’
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^~~~~~~~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: invalid conversion from ‘void*’ to ‘const btf*’ [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^
      |          |
      |          void*
/usr/include/bpf/btf.h:289:72: note:   initializing argument 1 of ‘btf_dump* btf_dump__new_deprecated(const btf*, const btf_ext*, const btf_dump_opts*, btf_dump_printf_fn_t)’
  289 | LIBBPF_API struct btf_dump *btf_dump__new_deprecated(const struct btf *btf,
      |                                                      ~~~~~~~~~~~~~~~~~~^~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: invalid conversion from ‘void*’ to ‘const btf_ext*’ [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^
      |          |
      |          void*
/usr/include/bpf/btf.h:290:76: note:   initializing argument 2 of ‘btf_dump* btf_dump__new_deprecated(const btf*, const btf_ext*, const btf_dump_opts*, btf_dump_printf_fn_t)’
  290 |                                                      const struct btf_ext *btf_ext,
      |                                                      ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: invalid conversion from ‘void*’ to ‘const btf_dump_opts*’ [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^
      |          |
      |          void*
/usr/include/bpf/btf.h:291:82: note:   initializing argument 3 of ‘btf_dump* btf_dump__new_deprecated(const btf*, const btf_ext*, const btf_dump_opts*, btf_dump_printf_fn_t)’
  291 |                                                      const struct btf_dump_opts *opts,
      |                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: invalid conversion from ‘void*’ to ‘btf_dump_printf_fn_t’ {aka ‘void (*)(void*, const char*, __va_list_tag*)’} [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^
      |          |
      |          void*
/usr/include/bpf/btf.h:292:75: note:   initializing argument 4 of ‘btf_dump* btf_dump__new_deprecated(const btf*, const btf_ext*, const btf_dump_opts*, btf_dump_printf_fn_t)’
  292 |                                                      btf_dump_printf_fn_t printf_fn);
      |                                                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: invalid conversion from ‘void*’ to ‘const btf*’ [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^
      |          |
      |          void*
/usr/include/bpf/btf.h:279:61: note:   initializing argument 1 of ‘btf_dump* btf_dump__new(const btf*, btf_dump_printf_fn_t, void*, const btf_dump_opts*)’
  279 | LIBBPF_API struct btf_dump *btf_dump__new(const struct btf *btf,
      |                                           ~~~~~~~~~~~~~~~~~~^~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: invalid conversion from ‘void*’ to ‘btf_dump_printf_fn_t’ {aka ‘void (*)(void*, const char*, __va_list_tag*)’} [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^
      |          |
      |          void*
/usr/include/bpf/btf.h:280:64: note:   initializing argument 2 of ‘btf_dump* btf_dump__new(const btf*, btf_dump_printf_fn_t, void*, const btf_dump_opts*)’
  280 |                                           btf_dump_printf_fn_t printf_fn,
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: invalid conversion from ‘void*’ to ‘const btf_dump_opts*’ [-fpermissive]
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^
      |          |
      |          void*
/usr/include/bpf/btf.h:282:71: note:   initializing argument 4 of ‘btf_dump* btf_dump__new(const btf*, btf_dump_printf_fn_t, void*, const btf_dump_opts*)’
  282 |                                           const struct btf_dump_opts *opts);
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: ‘__builtin_choose_expr’ was not declared in this scope; did you mean ‘__builtin_cexpl’?
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^~~~~~~~~~~~~

```

**Comment by martinetd** [comment]
fedora 35 has the inverse problem: they still ship [libbpf-0.6.1-2.fc35](https://koji.fedoraproject.org/koji/search?terms=libbpf-0.6.1-2.fc35&type=build&match=glob) which has the obsolete version.

Since fedora 36 is stable I'd suggest just upgrading, I'm not sure this is worth trying to support both variants here...

**Comment by viktormalik** [comment]
I proposed a fix for this in #2302, @caringi could you confirm that it works? Thanks!

**Comment by martinetd** [comment]
I was a bit hasty in my comment earlier but your patch won't help @viktormalik 

The problem is this:
```
/home/caringi/devel/bpftrace/src/btf.cpp: In function ‘btf_dump* bpftrace::dump_new(const btf*, btf_dump_printf_fn_t, void*)’:
/home/caringi/devel/bpftrace/src/btf.cpp:208:10: error: ‘typeof’ was not declared in this scope; did you mean ‘Type’?
  208 |   return btf_dump__new(btf, nullptr, &opts, dump_printf);
      |          ^~~~~~~~~~~~~
```
It's because the src/btf.h in that version of libbpf does not include the `ifndef __cplusplus`, which got added in 0.7.0 : https://github.com/libbpf/libbpf/commit/1321a8bb497584b22742ea69461811d4a6033a59

It's the bug I reported in see https://github.com/libbpf/libbpf/issues/283#issuecomment-986100727


So the problem isn't that we're using the wrong version of the lib, it's just really that libbpf 0.6.x is broken for c++ we cannot include btf.h at all. He really has no choice but to upgrade or locally patch his header.

**Comment by viktormalik** [comment]
Strange, I tried to compile with my patch on Fedora 35 (libbpf-0.6.1-2.fc35.x86_64) and it passed just fine. The trick is that the `typeof` is inside the `btf_dump__new` macro, but if we call `btf_dump__new_deprecated`, that macro should never expand.

Do you have a version of libbpf with that macro but without `btf_dump__new_deprecated`?

**Comment by martinetd** [comment]
Aaah. So the cmake checks fails because of the broken include. Sorry I didn't actually try, I didn't expect that.

Okay, I'll just shut up for now -- thanks :)

**Comment by caringi** [comment]
> I proposed a fix for this in #2302, @caringi could you confirm that it works? Thanks!

This fix solved the build problem on my F35. Thanks!
