### PR TITLE
fix git-clang-format link

### PR DESCRIPTION
**Pull request by dmitris**
Update the link to git-clang-format (`s/master/main`).

### CODE REVIEW

**Review by viktormalik — APPROVED** [review]

**Comment by viktormalik** [comment]
CI fails due to #2474 but since this is not a functional change, I'm merging it.
